defaults: &defaults
  white_ip_list: ''
  token_list: ''

  rtmp_server: '127.0.0.1:1985'
  rtmp_api: 'http://127.0.0.1:1985/api/v1'
  ffmpeg_bin: ''

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  ffmpeg_bin: ''
